// app
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

// token
const SET_TOKEN = 'SET_TOKEN'

// permission
const SET_ROUTES = 'SET_ROUTES'

// user
const SET_USER_NAME = 'SET_USER_NAME'
const SET_USER_AVATAR = 'SET_USER_AVATAR'
const SET_ROLES = 'SET_ROLES'
const SET_PERMISSIONS = 'SET_PERMISSIONS'
const SET_AUTH_TYPE = 'SET_AUTH_TYPE'
const SET_USER_INFO = 'SET_USER_INFO'

// tags view
const ADD_VISITED_VIEW = 'ADD_VISITED_VIEW'
const ADD_CACHED_VIEW = 'ADD_CACHED_VIEW'
const DEL_VISITED_VIEW = 'DEL_VISITED_VIEW'
const DEL_CACHED_VIEW = 'DEL_CACHED_VIEW'
const DEL_OTHERS_VISITED_VIEWS = 'DEL_OTHERS_VISITED_VIEWS'
const DEL_OTHERS_CACHED_VIEWS = 'DEL_OTHERS_CACHED_VIEWS'
const DEL_ALL_VISITED_VIEWS = 'DEL_ALL_VISITED_VIEWS'
const DEL_ALL_CACHED_VIEWS = 'DEL_ALL_CACHED_VIEWS'
const UPDATE_VISITED_VIEW = 'UPDATE_VISITED_VIEW'

export {
   SET_TOKEN,
   SET_ROUTES,
   SET_USER_NAME,
   SET_USER_AVATAR,
   SET_ROLES,
   SET_PERMISSIONS,
   TOGGLE_SIDEBAR,
   CLOSE_SIDEBAR,
   TOGGLE_DEVICE,
   ADD_VISITED_VIEW,
   ADD_CACHED_VIEW,
   DEL_VISITED_VIEW,
   DEL_CACHED_VIEW,
   DEL_OTHERS_VISITED_VIEWS,
   DEL_OTHERS_CACHED_VIEWS,
   DEL_ALL_VISITED_VIEWS,
   DEL_ALL_CACHED_VIEWS,
   UPDATE_VISITED_VIEW,
   SET_AUTH_TYPE,
   SET_USER_INFO
}
